Repository md-shamim-ahmad/LeetCode-Problem-Solution, pull requests merged in 2023-10, with the labels that each got.

#52 "2038. Remove Colored Pieces if Both Neighbors are the Same Color" C++ and Java Solution Code
  LeetCode Problems/2001 to 2100/2038. Remove Colored Pieces if Both Neighbors are the Same Color/2038. Remove Colored Pieces if Both Neighbors are the Same Color.cpp
  LeetCode Problems/2001 to 2100/2038. Remove Colored Pieces if Both Neighbors are the Same Color/2038. Remove Colored Pieces if Both Neighbors are the Same Color.java
  LeetCode Problems/2001 to 2100/2038. Remove Colored Pieces if Both Neighbors are the Same Color/README.md
Labels: enhancement, hacktoberfest-2023

#56 1512. Number of Good Pairs (October Daily Problem 2023)
  LeetCode Problems/1501 to 1600/1512. Number of Good Pairs/1512. Number of Good Pairs.cpp
  LeetCode Problems/1501 to 1600/1512. Number of Good Pairs/1512. Number of Good Pairs.java
  LeetCode Problems/1501 to 1600/1512. Number of Good Pairs/README.md
Labels: enhancement

#83 18. 4Sum Java Solution Added
  LeetCode Problems/1 to 100/18. 4Sum/18. 4Sum.java
  LeetCode Problems/1 to 100/18. 4Sum/README.md
Labels: hacktoberfest

#102 "343. Integer Break" Leetcode Solution Added
  LeetCode Problems/301 to 400/343. Integer Break/343. Integer Break.c
  LeetCode Problems/301 to 400/343. Integer Break/343. Integer Break.cpp
  LeetCode Problems/301 to 400/343. Integer Break/343. Integer Break.cs
  LeetCode Problems/301 to 400/343. Integer Break/343. Integer Break.java
  LeetCode Problems/301 to 400/343. Integer Break/343. Integer Break.js
  LeetCode Problems/301 to 400/343. Integer Break/343. Integer Break.kt
  LeetCode Problems/301 to 400/343. Integer Break/343. Integer Break.py
  LeetCode Problems/301 to 400/343. Integer Break/README.md
Labels: enhancement, hacktoberfest

#99 Added 13. Roman To Integer in Java Language
  LeetCode Problems/1 to 100/13. Roman to Integer/13. Roman to Integer.java
Labels: enhancement

#92 Create Two Sum.cs
  LeetCode Problems/1 to 100/1. Two Sum/1. Two Sum.cs
Labels: hacktoberfest-accepted

#115 Fixes #116, Add new solution to problem #4
  LeetCode Problems/1 to 100/4. Median of Two Sorted Arrays/4. Median of Two Sorted Arrays.java
Labels: hacktoberfest

#106 Update 141. Linked List Cycle.cpp
  LeetCode Problems/101 to 200/141. Linked List Cycle/141. Linked List Cycle.cpp
Labels: documentation, hacktoberfest-accepted

#100 added leetcode 14 java soln
  LeetCode Problems/1 to 100/14. Longest Common Prefix/14. Longest Common Prefix.java
Labels: documentation

#123 java solution to 283
  LeetCode Problems/201 to 300/283. Move Zeroes/283. Move Zeroes.java
  LeetCode Problems/201 to 300/283. Move Zeroes/README.md
Labels: hacktoberfest-accepted

#128 Added Solution of 41. Find Missing Positive and 59. Spiral Matrix 2
  LeetCode Problems/1 to 100/41. Find Missing Number/41. First Missing Positive.cpp
  LeetCode Problems/1 to 100/59. Spiral Matrix 2/59. Spiral Matrix 2.cpp
Labels: hacktoberfest-accepted

#127 Create First missing positive
  LeetCode Problems/1 to 100/41. First Missing Positive/README.md
Labels: wontfix, hacktoberfest
